// ── DEMO MOCK DATA for frontend preview ──────────────────────
// This file provides realistic mock data so the UI can be
// explored without a running backend. Remove when backend is ready.

import { User, Project, Task, ActivityLog } from "@/types";

export const MOCK_USERS: User[] = [
  {
    id: "u1",
    name: "Alex Johnson",
    email: "admin@taskflow.com",
    role: "ADMIN",
    createdAt: "2026-01-10T08:00:00Z",
    updatedAt: "2026-07-01T08:00:00Z",
  },
  {
    id: "u2",
    name: "Sarah Chen",
    email: "manager@taskflow.com",
    role: "MANAGER",
    createdAt: "2026-02-14T08:00:00Z",
    updatedAt: "2026-07-01T08:00:00Z",
  },
  {
    id: "u3",
    name: "Marcus Rivera",
    email: "member@taskflow.com",
    role: "MEMBER",
    createdAt: "2026-03-01T08:00:00Z",
    updatedAt: "2026-07-01T08:00:00Z",
  },
  {
    id: "u4",
    name: "Priya Kapoor",
    email: "priya@taskflow.com",
    role: "MEMBER",
    createdAt: "2026-03-15T08:00:00Z",
    updatedAt: "2026-07-01T08:00:00Z",
  },
  {
    id: "u5",
    name: "James Walker",
    email: "james@taskflow.com",
    role: "MANAGER",
    createdAt: "2026-04-01T08:00:00Z",
    updatedAt: "2026-07-01T08:00:00Z",
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: "t1",
    title: "Design system setup",
    description: "Set up Tailwind config, color tokens, and global styles.",
    status: "COMPLETED",
    priority: "HIGH",
    projectId: "p1",
    project: {} as Project,
    assigneeId: "u3",
    assignee: MOCK_USERS[2],
    assigneeIds: ["u3"],
    assignees: [MOCK_USERS[2]],
    createdAt: "2026-06-01T09:00:00Z",
    updatedAt: "2026-06-10T09:00:00Z",
  },
  {
    id: "t2",
    title: "Build authentication flow",
    description: "JWT login, register, and protected routes with RBAC.",
    status: "COMPLETED",
    priority: "HIGH",
    projectId: "p1",
    project: {} as Project,
    assigneeId: "u2",
    assignee: MOCK_USERS[1],
    assigneeIds: ["u2"],
    assignees: [MOCK_USERS[1]],
    createdAt: "2026-06-05T09:00:00Z",
    updatedAt: "2026-06-15T09:00:00Z",
  },
  {
    id: "t3",
    title: "Implement Kanban board",
    description: "Drag-and-drop task board with @hello-pangea/dnd.",
    status: "IN_PROGRESS",
    priority: "HIGH",
    projectId: "p1",
    project: {} as Project,
    assigneeId: "u3",
    assignee: MOCK_USERS[2],
    assigneeIds: ["u3"],
    assignees: [MOCK_USERS[2]],
    createdAt: "2026-06-12T09:00:00Z",
    updatedAt: "2026-07-01T09:00:00Z",
  },
  {
    id: "t4",
    title: "Activity audit trail",
    description: "Log all user actions and display in a timeline feed.",
    status: "IN_PROGRESS",
    priority: "MEDIUM",
    projectId: "p1",
    project: {} as Project,
    assigneeId: "u4",
    assignee: MOCK_USERS[3],
    assigneeIds: ["u4"],
    assignees: [MOCK_USERS[3]],
    createdAt: "2026-06-18T09:00:00Z",
    updatedAt: "2026-07-05T09:00:00Z",
  },
  {
    id: "t5",
    title: "Write API documentation",
    description: "Document all REST endpoints with request/response examples.",
    status: "TODO",
    priority: "LOW",
    projectId: "p1",
    project: {} as Project,
    assigneeId: "u5",
    assignee: MOCK_USERS[4],
    assigneeIds: ["u5"],
    assignees: [MOCK_USERS[4]],
    createdAt: "2026-07-01T09:00:00Z",
    updatedAt: "2026-07-01T09:00:00Z",
  },
  {
    id: "t6",
    title: "Set up CI/CD pipeline",
    description: "GitHub Actions for lint, typecheck, and build on PR.",
    status: "TODO",
    priority: "MEDIUM",
    projectId: "p2",
    project: {} as Project,
    assigneeId: "u3",
    assignee: MOCK_USERS[2],
    assigneeIds: ["u3"],
    assignees: [MOCK_USERS[2]],
    createdAt: "2026-07-05T09:00:00Z",
    updatedAt: "2026-07-05T09:00:00Z",
  },
  {
    id: "t7",
    title: "Database schema design",
    description: "Define Prisma models for users, projects, tasks, activity.",
    status: "COMPLETED",
    priority: "HIGH",
    projectId: "p2",
    project: {} as Project,
    assigneeId: "u2",
    assignee: MOCK_USERS[1],
    assigneeIds: ["u2"],
    assignees: [MOCK_USERS[1]],
    createdAt: "2026-06-20T09:00:00Z",
    updatedAt: "2026-06-28T09:00:00Z",
  },
  {
    id: "t8",
    title: "Performance testing",
    description: "Load test the API endpoints with k6.",
    status: "TODO",
    priority: "LOW",
    projectId: "p2",
    project: {} as Project,
    assigneeId: "u4",
    assignee: MOCK_USERS[3],
    assigneeIds: ["u4"],
    assignees: [MOCK_USERS[3]],
    createdAt: "2026-07-08T09:00:00Z",
    updatedAt: "2026-07-08T09:00:00Z",
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: "p1",
    name: "TaskFlow Platform",
    description:
      "A production-ready project and team management platform with role-based access, Kanban board, and real-time activity tracking.",
    managerId: "u2",
    manager: MOCK_USERS[1],
    members: [MOCK_USERS[2], MOCK_USERS[3], MOCK_USERS[4]],
    tasks: MOCK_TASKS.filter((t) => t.projectId === "p1"),
    createdAt: "2026-06-01T08:00:00Z",
    updatedAt: "2026-07-10T08:00:00Z",
  },
  {
    id: "p2",
    name: "API Infrastructure",
    description:
      "Backend API services, database design, deployment pipeline, and performance monitoring for the platform.",
    managerId: "u5",
    manager: MOCK_USERS[4],
    members: [MOCK_USERS[1], MOCK_USERS[3]],
    tasks: MOCK_TASKS.filter((t) => t.projectId === "p2"),
    createdAt: "2026-06-15T08:00:00Z",
    updatedAt: "2026-07-08T08:00:00Z",
  },
  {
    id: "p3",
    name: "Mobile App MVP",
    description:
      "React Native mobile companion app for TaskFlow — view tasks, update status, and get push notifications.",
    managerId: "u2",
    manager: MOCK_USERS[1],
    members: [MOCK_USERS[2]],
    tasks: [],
    createdAt: "2026-07-01T08:00:00Z",
    updatedAt: "2026-07-01T08:00:00Z",
  },
];

// Fix circular reference in tasks
MOCK_TASKS.forEach((task) => {
  task.project = MOCK_PROJECTS.find((p) => p.id === task.projectId) || ({} as Project);
});

export const MOCK_ACTIVITY: ActivityLog[] = [
  {
    id: "a1",
    action: "created project \"TaskFlow Platform\"",
    userId: "u2",
    user: MOCK_USERS[1],
    projectId: "p1",
    taskId: null,
    createdAt: "2026-06-01T08:05:00Z",
  },
  {
    id: "a2",
    action: "added Marcus Rivera to TaskFlow Platform",
    userId: "u2",
    user: MOCK_USERS[1],
    projectId: "p1",
    taskId: null,
    createdAt: "2026-06-02T09:00:00Z",
  },
  {
    id: "a3",
    action: "created task \"Design system setup\" with HIGH priority",
    userId: "u2",
    user: MOCK_USERS[1],
    projectId: "p1",
    taskId: "t1",
    createdAt: "2026-06-05T10:00:00Z",
  },
  {
    id: "a4",
    action: "changed task \"Design system setup\" to COMPLETED",
    userId: "u3",
    user: MOCK_USERS[2],
    projectId: "p1",
    taskId: "t1",
    createdAt: "2026-06-10T14:30:00Z",
  },
  {
    id: "a5",
    action: "created task \"Build authentication flow\"",
    userId: "u2",
    user: MOCK_USERS[1],
    projectId: "p1",
    taskId: "t2",
    createdAt: "2026-06-12T08:00:00Z",
  },
  {
    id: "a6",
    action: "changed task \"Implement Kanban board\" to IN_PROGRESS",
    userId: "u3",
    user: MOCK_USERS[2],
    projectId: "p1",
    taskId: "t3",
    createdAt: "2026-07-01T11:00:00Z",
  },
  {
    id: "a7",
    action: "created project \"API Infrastructure\"",
    userId: "u5",
    user: MOCK_USERS[4],
    projectId: "p2",
    taskId: null,
    createdAt: "2026-06-15T08:00:00Z",
  },
  {
    id: "a8",
    action: "assigned Priya Kapoor to task \"Activity audit trail\"",
    userId: "u2",
    user: MOCK_USERS[1],
    projectId: "p1",
    taskId: "t4",
    createdAt: "2026-07-05T09:30:00Z",
  },
  {
    id: "a9",
    action: "created task \"Set up CI/CD pipeline\"",
    userId: "u5",
    user: MOCK_USERS[4],
    projectId: "p2",
    taskId: "t6",
    createdAt: "2026-07-05T10:00:00Z",
  },
  {
    id: "a10",
    action: "created project \"Mobile App MVP\"",
    userId: "u2",
    user: MOCK_USERS[1],
    projectId: "p3",
    taskId: null,
    createdAt: "2026-07-01T08:00:00Z",
  },
];
